language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
  yarn: true
install: yarn install --pure-lockfile
script:
  - yarn run lint
  - yarn run test
  - yarn run build
notifications:
  slack: 'kleros:Ub8n81EgKJ3iRrMDyWyQIVJp'
